"""Created owner_id column on Stores

Revision ID: 3f10cefbd20d
Revises: 9730c701ae21
Create Date: 2025-02-22 20:17:50.479724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f10cefbd20d'
down_revision: Union[str, None] = '9730c701ae21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('stores', 'owner_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'owner_id')
    # ### end Alembic commands ###
