"""Removed location and owner from Stores

Revision ID: 9730c701ae21
Revises: fb51fb9c7e56
Create Date: 2025-02-22 20:07:39.913373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9730c701ae21'
down_revision: Union[str, None] = 'fb51fb9c7e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'location')
    op.drop_column('stores', 'owner')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
