"""Created owner_id foreign key

Revision ID: d37bfc56dd54
Revises: 3f10cefbd20d
Create Date: 2025-02-22 20:23:46.502251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd37bfc56dd54'
down_revision: Union[str, None] = '3f10cefbd20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    # ### end Alembic commands ###
